-- MySQL Script generated by MySQL Workbench
-- Wed Nov 28 23:18:24 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering


CREATE TABLE Fonte
(
  `cd_fonte` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nm_descricao` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`cd_fonte`)
);


-- -----------------------------------------------------
-- Table `mvp_pesquisa`.`UF`
-- -----------------------------------------------------

CREATE TABLE UF
(
  `cd_uf` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `sigla_uf` CHAR(2) NOT NULL,
  `nome` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`cd_uf`)
);


-- -----------------------------------------------------
-- Table `mvp_pesquisa`.`Cidade`
-- -----------------------------------------------------

CREATE TABLE Cidade
(
  `cd_cidade` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome_cidade` VARCHAR(50) NULL,
  PRIMARY KEY (`cd_cidade`)
);



-- -----------------------------------------------------
-- Table `mvp_pesquisa`.`Municipio`
-- -----------------------------------------------------

CREATE TABLE Municipio
(
  `cd_municipio` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome_municipio` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`cd_municipio`)
);


-- -----------------------------------------------------
-- Table `mvp_pesquisa`.`Faixa_Etaria`
-- -----------------------------------------------------

CREATE TABLE Faixa_Etaria
(
  `cd_faixa_etaria` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `desc_idade` VARCHAR(20) NOT NULL COMMENT 'Multivalorado com as seguintes opções:\n1. menos de 20 anos\n2. 21 a 30 anos\n3. 31 a 40 anos\n4. 41 a 50 anos\n5. 51 a 60 anos\n6. 61 a 70 anos\n7. mais de 70 anos',
  PRIMARY KEY (`cd_faixa_etaria`)
);


-- -----------------------------------------------------
-- Table `mvp_pesquisa`.`Estado_Civil`
-- -----------------------------------------------------

CREATE TABLE Estado_Civil
(
  `cd_estado_civil`   INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `desc_estado_civil` VARCHAR(20) NULL COMMENT 'A descrição e multivalorada \n1. solteiro \n2. casado\n3. separado\n4. divorciado/desquitado\n5. viúvo ',
  PRIMARY KEY (`cd_estado_civil`)
);


-- -----------------------------------------------------
-- Table `mvp_pesquisa`.`Renda`
-- -----------------------------------------------------
CREATE TABLE Renda
(
  `cd_renda` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `desc_renda` VARCHAR(20) NULL COMMENT 'Descrição da renda:\n1. de 700 a 1024\n2. de 1025 a 1704\n3. de 1705 a 2832\n4. de 2833 a 5346\n5 . mais de 5347',
  PRIMARY KEY (`cd_renda`)
);

-- -----------------------------------------------------
-- Table `mvp_pesquisa`.`Educacao`
-- -----------------------------------------------------
CREATE TABLE Educacao
(
  `cd_instrucao`   INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `desc_instrucao` INT NOT NULL COMMENT 'Tipo:\n\n1 -> Analfabeto / primeiro incompleto\n2 -> Primário Completo / Ginásio Incompleto\n3 -> Ginásio Completo / Colégial Incompleto\n4 -> Colégio Completo / Superior Incompleto\n5 -> Superior Completo',
  PRIMARY KEY (`cd_instrucao`)
);



-- -----------------------------------------------------
-- Table `mvp_pesquisa`.`Profissao`
-- -----------------------------------------------------

CREATE TABLE Profissao
(
  `cd_profissao` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `desc_profissao` VARCHAR(40) NOT NULL COMMENT 'Descrição da Profissão (Alfanumérico, Tamanho: 40). Valores possíveis: \n1. diretor e gerente\n2. profissionais cientistas e intelectuais\n3. tecnicos e profissões nível médio\n4. trabalhadores de apoio administrativo\n5. trabalhadores de serviços, vendedores comerciais e mercado\n6. trababalhores qualificados agropecuária floresta e caça\n7. trabalhadores qualificados artesãos\n8. operadores de instalações, maquinas e montagens\n9. ocupações elementares\n0. membros das FA`s policia bombeiros',
  PRIMARY KEY (`cd_profissao`)
);


-- -----------------------------------------------------
-- Table `mvp_pesquisa`.`Posicao_Trabalho`
-- -----------------------------------------------------

CREATE TABLE Posicao_Trabalho
(
  `cd_posicao_trabalho` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `desc_posicao_trabalho` VARCHAR(20) NOT NULL COMMENT 'Descrição da da Posição Trabalho (Alfanumérico, Tamanho: 20). Valores possíveis:  \n\n1. patrão\n2. diretor com chefia de funcionários\n3. diretor\n4. gerente com chefia de funcionários\n5. gerente\n6. quadro médio \n7. funcionário administrativo',
  PRIMARY KEY (`cd_posicao_trabalho`)
);

-- -----------------------------------------------------
-- Table `mvp_pesquisa`.`Respondente`
-- -----------------------------------------------------
CREATE TABLE Respondente
(
  `cd_numero_registro` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `cd_individuo` INT UNSIGNED NOT NULL,
  `cd_fk_tab_fonte` INT UNSIGNED NOT NULL,
  `cd_cpf` INT(11) UNSIGNED NOT NULL,
  `nome` VARCHAR(100) NOT NULL,
  `email` VARCHAR(40) NOT NULL,
  `telefone_fixo` INT(30) NOT NULL,
  `telefone_cel` INT(30) NOT NULL,
  `cep` INT(8) NOT NULL,
  `cd_fk_tab_estado` INT UNSIGNED NOT NULL,
  `cd_fk_tab_cidade` INT UNSIGNED NOT NULL,
  `cd_fk_tab_municipio` INT UNSIGNED NOT NULL,
  `sexo` INT NOT NULL COMMENT 'Sexo Tipo Alpha Numerico \n1 -> Masculino\n2 -> Feminio\n3-> Indefinido',
  `data_nascimento` DATE NOT NULL,
  `cd_fk_tab_faixa_etaria` INT UNSIGNED NOT NULL,
  `cd_fk_tab_estado_civil` INT UNSIGNED NOT NULL,
  `classe_social` CHAR(1) NOT NULL COMMENT 'Tipos:\n1 -> A;\n2 -> B;\n3 -> C;\n4 -> D;\n5 -> E;',
  `cd_fk_tab_educacao` INT UNSIGNED NOT NULL,
  `cd_fk_tab_renda` INT UNSIGNED NOT NULL,
  `cd_fk_tab_profissao` INT UNSIGNED NOT NULL,
  `cd_fk_posicao_trabalho` INT UNSIGNED NOT NULL,
  `moradia` INT NOT NULL COMMENT 'Tipo:\n1 -> Casa Própria;\n2 -> Apartamemto Próprio\n3 -> Casa Alugada\n4 -> Apartemento Alugado',
  `moradia_lazer` INT NOT NULL COMMENT 'Tipo:\n\n1 -> Casa própria na praia;\n2 -> Casa própria no campo;',
  `auxiliar_do_lar` INT NOT NULL COMMENT 'Tipo:\n\n1 -> Empregada permanente;\n2 -> Diarista;',
  `possui_carro` TINYINT NOT NULL,
  `raca` INT NOT NULL COMMENT 'Tipo\n\n1 -> Branca\n2 -> Preta\n3 -> Amarela\n4 -> Parda\n5 -> Indígena\n\n',
  PRIMARY KEY (`cd_numero_registro`)
);


/*
  Data Carga
 */
-- --
Insert Into uf (cd_uf, sigla_uf, nome)
Values (12, 'AC', 'Acre');
Insert Into uf (cd_uf, sigla_uf, nome)
Values (27, 'AL', 'Alagoas');
Insert Into uf (cd_uf, sigla_uf, nome)
Values (13, 'AM', 'Amazonas');
Insert Into uf (cd_uf, sigla_uf, nome)
Values (16, 'AP', 'Amapá');
Insert Into uf (cd_uf, sigla_uf, nome)
Values (29, 'BA', 'Bahia');
Insert Into uf (cd_uf, sigla_uf, nome)
Values (23, 'CE', 'Ceará');
Insert Into uf (cd_uf, sigla_uf, nome)
Values (53, 'DF', 'Distrito Federal');
Insert Into uf (cd_uf, sigla_uf, nome)
Values (32, 'ES', 'Espírito Santo');
Insert Into uf (cd_uf, sigla_uf, nome)
Values (52, 'GO', 'Goiás');
Insert Into uf (cd_uf, sigla_uf, nome)
Values (21, 'MA', 'Maranhão');
Insert Into uf (cd_uf, sigla_uf, nome)
Values (31, 'MG', 'Minas Gerais');
Insert Into uf (cd_uf, sigla_uf, nome)
Values (50, 'MS', 'Mato Grosso do Sul');
Insert Into uf (cd_uf, sigla_uf, nome)
Values (51, 'MT', 'Mato Grosso');
Insert Into uf (cd_uf, sigla_uf, nome)
Values (15, 'PA', 'Pará');
Insert Into uf (cd_uf, sigla_uf, nome)
Values (25, 'PB', 'Paraíba');
Insert Into uf (cd_uf, sigla_uf, nome)
Values (26, 'PE', 'Pernambuco');
Insert Into uf (cd_uf, sigla_uf, nome)
Values (22, 'PI', 'Piauí');
Insert Into uf (cd_uf, sigla_uf, nome)
Values (41, 'PR', 'Paraná');
Insert Into uf (cd_uf, sigla_uf, nome)
Values (33, 'RJ', 'Rio de Janeiro');
Insert Into uf (cd_uf, sigla_uf, nome)
Values (24, 'RN', 'Rio Grande do Norte');
Insert Into uf (cd_uf, sigla_uf, nome)
Values (11, 'RO', 'Rondônia');
Insert Into uf (cd_uf, sigla_uf, nome)
Values (14, 'RR', 'Roraima');
Insert Into uf (cd_uf, sigla_uf, nome)
Values (43, 'RS', 'Rio Grande do Sul');
Insert Into uf (cd_uf, sigla_uf, nome)
Values (42, 'SC', 'Santa Catarina');
Insert Into uf (cd_uf, sigla_uf, nome)
Values (28, 'SE', 'Sergipe');
Insert Into uf (cd_uf, sigla_uf, nome)
Values (35, 'SP', 'São Paulo');
Insert Into uf (cd_uf, sigla_uf, nome)
Values (17, 'TO', 'Tocantins');
