-- MySQL Script generated by MySQL Workbench
-- Sun Dec  2 13:05:00 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mvp_pesquisa
-- -----------------------------------------------------
-- Banco de Estudo da Cadeira de BD 1
DROP SCHEMA IF EXISTS `mvp_pesquisa` ;

-- -----------------------------------------------------
-- Schema mvp_pesquisa
--
-- Banco de Estudo da Cadeira de BD 1
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mvp_pesquisa` DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ;
USE `mvp_pesquisa` ;

-- -----------------------------------------------------
-- Table `mvp_pesquisa`.`Fonte`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mvp_pesquisa`.`Fonte` ;

CREATE TABLE IF NOT EXISTS `mvp_pesquisa`.`Fonte` (
  `cd_fonte` INT NOT NULL AUTO_INCREMENT,
  `nm_descricao` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`cd_fonte`),
  UNIQUE INDEX `cd_fonte_UNIQUE` (`cd_fonte` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mvp_pesquisa`.`UF`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mvp_pesquisa`.`UF` ;

CREATE TABLE IF NOT EXISTS `mvp_pesquisa`.`UF` (
  `cd_uf` INT NOT NULL AUTO_INCREMENT,
  `sigla_uf` CHAR(2) NOT NULL,
  `nome` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`cd_uf`),
  UNIQUE INDEX `cd_uf_UNIQUE` (`cd_uf` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mvp_pesquisa`.`Cidade`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mvp_pesquisa`.`Cidade` ;

CREATE TABLE IF NOT EXISTS `mvp_pesquisa`.`Cidade` (
  `cd_cidade` INT NOT NULL AUTO_INCREMENT,
  `nome_cidade` VARCHAR(50) NULL,
  PRIMARY KEY (`cd_cidade`),
  UNIQUE INDEX `cd_cidade_UNIQUE` (`cd_cidade` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mvp_pesquisa`.`Municipio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mvp_pesquisa`.`Municipio` ;

CREATE TABLE IF NOT EXISTS `mvp_pesquisa`.`Municipio` (
  `cd_municipio` INT NOT NULL AUTO_INCREMENT,
  `nome_municipio` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`cd_municipio`),
  UNIQUE INDEX `cd_municipio_UNIQUE` (`cd_municipio` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mvp_pesquisa`.`Faixa_Etaria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mvp_pesquisa`.`Faixa_Etaria` ;

CREATE TABLE IF NOT EXISTS `mvp_pesquisa`.`Faixa_Etaria` (
  `cd_faixa_etaria` INT NOT NULL AUTO_INCREMENT,
  `desc_idade` VARCHAR(20) NOT NULL COMMENT 'Multivalorado com as seguintes opções:\n1. menos de 20 anos\n2. 21 a 30 anos\n3. 31 a 40 anos\n4. 41 a 50 anos\n5. 51 a 60 anos\n6. 61 a 70 anos\n7. mais de 70 anos',
  PRIMARY KEY (`cd_faixa_etaria`),
  UNIQUE INDEX `cd_faixa_etaria_UNIQUE` (`cd_faixa_etaria` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mvp_pesquisa`.`Estado_Civil`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mvp_pesquisa`.`Estado_Civil` ;

CREATE TABLE IF NOT EXISTS `mvp_pesquisa`.`Estado_Civil` (
  `cd_estado_civil` INT NOT NULL AUTO_INCREMENT,
  `desc_estado_civil` VARCHAR(20) NULL COMMENT 'A descrição e multivalorada \n1. solteiro \n2. casado\n3. separado\n4. divorciado/desquitado\n5. viúvo ',
  PRIMARY KEY (`cd_estado_civil`),
  UNIQUE INDEX `cd_estado_civil_UNIQUE` (`cd_estado_civil` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mvp_pesquisa`.`Renda`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mvp_pesquisa`.`Renda` ;

CREATE TABLE IF NOT EXISTS `mvp_pesquisa`.`Renda` (
  `cd_renda` INT NOT NULL AUTO_INCREMENT,
  `desc_renda` VARCHAR(100) NULL COMMENT 'Descrição da renda:\n1. de 700 a 1024\n2. de 1025 a 1704\n3. de 1705 a 2832\n4. de 2833 a 5346\n5 . mais de 5347',
  PRIMARY KEY (`cd_renda`),
  UNIQUE INDEX `cd_renda_UNIQUE` (`cd_renda` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mvp_pesquisa`.`Educacao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mvp_pesquisa`.`Educacao` ;

CREATE TABLE IF NOT EXISTS `mvp_pesquisa`.`Educacao` (
  `cd_instrucao` INT NOT NULL AUTO_INCREMENT,
  `desc_instrucao` VARCHAR(200) NOT NULL COMMENT 'Tipo:\n\n1 -> Analfabeto / primeiro incompleto\n2 -> Primário Completo / Ginásio Incompleto\n3 -> Ginásio Completo / Colégial Incompleto\n4 -> Colégio Completo / Superior Incompleto\n5 -> Superior Completo',
  PRIMARY KEY (`cd_instrucao`),
  UNIQUE INDEX `cd_instrucao_UNIQUE` (`cd_instrucao` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mvp_pesquisa`.`Posicao_Trabalho`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mvp_pesquisa`.`Posicao_Trabalho` ;

CREATE TABLE IF NOT EXISTS `mvp_pesquisa`.`Posicao_Trabalho` (
  `cd_posicao_trabalho` INT NOT NULL AUTO_INCREMENT,
  `desc_posicao_trabalho` VARCHAR(255) NOT NULL COMMENT 'Descrição da da Posição Trabalho (Alfanumérico, Tamanho: 20). Valores possíveis:  \n\n1. patrão\n2. diretor com chefia de funcionários\n3. diretor\n4. gerente com chefia de funcionários\n5. gerente\n6. quadro médio \n7. funcionário administrativo',
  PRIMARY KEY (`cd_posicao_trabalho`),
  UNIQUE INDEX `cd_posicao_trabalho_UNIQUE` (`cd_posicao_trabalho` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mvp_pesquisa`.`Profissao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mvp_pesquisa`.`Profissao` ;

CREATE TABLE IF NOT EXISTS `mvp_pesquisa`.`Profissao` (
  `cd_profissao` INT NOT NULL AUTO_INCREMENT,
  `desc_profissao` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`cd_profissao`),
  UNIQUE INDEX `cdProfissao_UNIQUE` (`cd_profissao` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mvp_pesquisa`.`Respondente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mvp_pesquisa`.`Respondente` ;

CREATE TABLE IF NOT EXISTS `mvp_pesquisa`.`Respondente` (
  `cd_numero_registro` INT NOT NULL AUTO_INCREMENT,
  `cd_individuo` INT NOT NULL,
  `cd_fk_tab_fonte` INT NOT NULL,
  `cd_cpf` VARCHAR(11) NOT NULL,
  `nome` VARCHAR(100) NOT NULL,
  `email` VARCHAR(40) NOT NULL,
  `telefone_fixo` VARCHAR(50) NOT NULL,
  `telefone_cel` VARCHAR(50) NOT NULL,
  `cep` VARCHAR(20) NOT NULL,
  `cd_fk_tab_estado` INT NOT NULL,
  `cd_fk_tab_cidade` INT NOT NULL,
  `cd_fk_tab_municipio` INT NOT NULL,
  `sexo` INT NOT NULL COMMENT 'Sexo Tipo Alpha Numerico \n1 -> Masculino\n2 -> Feminio\n3-> Indefinido',
  `data_nascimento` TIMESTAMP NOT NULL COMMENT '\n',
  `cd_fk_tab_faixa_etaria` INT NOT NULL,
  `cd_fk_tab_estado_civil` INT NOT NULL,
  `classe_social` CHAR(1) NOT NULL COMMENT 'Tipos:\n1 -> A;\n2 -> B;\n3 -> C;\n4 -> D;\n5 -> E;',
  `cd_fk_tab_educacao` INT NOT NULL,
  `cd_fk_tab_renda` INT NOT NULL,
  `cd_fk_tab_profissao` INT NOT NULL,
  `cd_fk_posicao_trabalho` INT NOT NULL,
  `moradia` INT NOT NULL COMMENT 'Tipo:\n1 -> Casa Própria;\n2 -> Apartamemto Próprio\n3 -> Casa Alugada\n4 -> Apartemento Alugado',
  `moradia_lazer` INT NOT NULL COMMENT 'Tipo:\n\n1 -> Casa própria na praia;\n2 -> Casa própria no campo;',
  `auxiliar_do_lar` INT NOT NULL COMMENT 'Tipo:\n\n1 -> Empregada permanente;\n2 -> Diarista;',
  `possui_carro` TINYINT NOT NULL,
  `raca` INT NOT NULL COMMENT 'Tipo\n\n1 -> Branca\n2 -> Preta\n3 -> Amarela\n4 -> Parda\n5 -> Indígena\n\n',
  PRIMARY KEY (`cd_numero_registro`),
  UNIQUE INDEX `cd_fk_tab_fonte_UNIQUE` (`cd_fk_tab_fonte` ASC) VISIBLE,
  UNIQUE INDEX `cd_individuo_UNIQUE` (`cd_individuo` ASC) VISIBLE,
  UNIQUE INDEX `cd_numero_registro_UNIQUE` (`cd_numero_registro` ASC) VISIBLE,
  UNIQUE INDEX `cd_cpf_UNIQUE` (`cd_cpf` ASC) VISIBLE,
  UNIQUE INDEX `cd_fk_tab_estado_UNIQUE` (`cd_fk_tab_estado` ASC) VISIBLE,
  UNIQUE INDEX `cd_fk_tab_cidade_UNIQUE` (`cd_fk_tab_cidade` ASC) VISIBLE,
  UNIQUE INDEX `cd_fk_tab_municipio_UNIQUE` (`cd_fk_tab_municipio` ASC) VISIBLE,
  UNIQUE INDEX `data_nascimento_UNIQUE` (`data_nascimento` ASC) VISIBLE,
  UNIQUE INDEX `cd_fk_tab_faixa_etaria_UNIQUE` (`cd_fk_tab_faixa_etaria` ASC) VISIBLE,
  UNIQUE INDEX `cd_fk_tab_estado_civil_UNIQUE` (`cd_fk_tab_estado_civil` ASC) VISIBLE,
  UNIQUE INDEX `cd_fk_tab_educacao_UNIQUE` (`cd_fk_tab_educacao` ASC) VISIBLE,
  UNIQUE INDEX `cd_fk_tab_renda_UNIQUE` (`cd_fk_tab_renda` ASC) VISIBLE,
  UNIQUE INDEX `cd_fk_tab_profissao_UNIQUE` (`cd_fk_tab_profissao` ASC) VISIBLE,
  UNIQUE INDEX `cd_fk_posicao_trabalho_UNIQUE` (`cd_fk_posicao_trabalho` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mvp_pesquisa`.``
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mvp_pesquisa`.`` ;

CREATE TABLE IF NOT EXISTS `mvp_pesquisa`.`` (
  `id` INT NOT NULL,
  `Telefone_Fixo` VARCHAR(100) NULL,
  `Telefone_Cel` VARCHAR(100) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mvp_pesquisa`.`Usuario_Admin`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mvp_pesquisa`.`Usuario_Admin` ;

CREATE TABLE IF NOT EXISTS `mvp_pesquisa`.`Usuario_Admin` (
  `id_user_sistema` INT NOT NULL AUTO_INCREMENT,
  `nome_user` VARCHAR(50) NOT NULL,
  `config_user` VARCHAR(45) NOT NULL,
  `senha_user` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_user_sistema`),
  UNIQUE INDEX `id_user_sistema_UNIQUE` (`id_user_sistema` ASC) VISIBLE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `mvp_pesquisa`.`Fonte`
-- -----------------------------------------------------
START TRANSACTION;
USE `mvp_pesquisa`;
INSERT INTO `mvp_pesquisa`.`Fonte` (`cd_fonte`, `nm_descricao`) VALUES (1, 'Casa Bahia');
INSERT INTO `mvp_pesquisa`.`Fonte` (`cd_fonte`, `nm_descricao`) VALUES (2, 'Diario do Nordeste');
INSERT INTO `mvp_pesquisa`.`Fonte` (`cd_fonte`, `nm_descricao`) VALUES (3 , 'Data Folha');
INSERT INTO `mvp_pesquisa`.`Fonte` (`cd_fonte`, `nm_descricao`) VALUES (4, 'Ibope');

COMMIT;


-- -----------------------------------------------------
-- Data for table `mvp_pesquisa`.`Faixa_Etaria`
-- -----------------------------------------------------
START TRANSACTION;
USE `mvp_pesquisa`;
INSERT INTO `mvp_pesquisa`.`Faixa_Etaria` (`cd_faixa_etaria`, `desc_idade`) VALUES (1, 'menos de 20 anos');
INSERT INTO `mvp_pesquisa`.`Faixa_Etaria` (`cd_faixa_etaria`, `desc_idade`) VALUES (2, '21 a 30 anos');
INSERT INTO `mvp_pesquisa`.`Faixa_Etaria` (`cd_faixa_etaria`, `desc_idade`) VALUES (3, '31 a 40 anos');
INSERT INTO `mvp_pesquisa`.`Faixa_Etaria` (`cd_faixa_etaria`, `desc_idade`) VALUES (4, '41 a 50 anos');
INSERT INTO `mvp_pesquisa`.`Faixa_Etaria` (`cd_faixa_etaria`, `desc_idade`) VALUES (5, '51 a 60 anos');
INSERT INTO `mvp_pesquisa`.`Faixa_Etaria` (`cd_faixa_etaria`, `desc_idade`) VALUES (6, '61 a 70 anos ');
INSERT INTO `mvp_pesquisa`.`Faixa_Etaria` (`cd_faixa_etaria`, `desc_idade`) VALUES (7, 'mais de 70 anos');

COMMIT;


-- -----------------------------------------------------
-- Data for table `mvp_pesquisa`.`Estado_Civil`
-- -----------------------------------------------------
START TRANSACTION;
USE `mvp_pesquisa`;
INSERT INTO `mvp_pesquisa`.`Estado_Civil` (`cd_estado_civil`, `desc_estado_civil`) VALUES (1, 'solteiro');
INSERT INTO `mvp_pesquisa`.`Estado_Civil` (`cd_estado_civil`, `desc_estado_civil`) VALUES (2, 'separado');
INSERT INTO `mvp_pesquisa`.`Estado_Civil` (`cd_estado_civil`, `desc_estado_civil`) VALUES (3, 'divorciado');
INSERT INTO `mvp_pesquisa`.`Estado_Civil` (`cd_estado_civil`, `desc_estado_civil`) VALUES (4, 'viuvo');

COMMIT;


-- -----------------------------------------------------
-- Data for table `mvp_pesquisa`.`Renda`
-- -----------------------------------------------------
START TRANSACTION;
USE `mvp_pesquisa`;
INSERT INTO `mvp_pesquisa`.`Renda` (`cd_renda`, `desc_renda`) VALUES (1, 'R$ 700,00 a R$ 1.024,00');
INSERT INTO `mvp_pesquisa`.`Renda` (`cd_renda`, `desc_renda`) VALUES (2, 'R$ 1.025,00 a R$ 1.704,00');
INSERT INTO `mvp_pesquisa`.`Renda` (`cd_renda`, `desc_renda`) VALUES (3, 'R$ 1.705,00 a R$ 2.832,00');
INSERT INTO `mvp_pesquisa`.`Renda` (`cd_renda`, `desc_renda`) VALUES (4, 'R$ 2.833,00 a R$ 5.346,00');
INSERT INTO `mvp_pesquisa`.`Renda` (`cd_renda`, `desc_renda`) VALUES (5, 'acima de R$ 5.347,00');

COMMIT;


-- -----------------------------------------------------
-- Data for table `mvp_pesquisa`.`Educacao`
-- -----------------------------------------------------
START TRANSACTION;
USE `mvp_pesquisa`;
INSERT INTO `mvp_pesquisa`.`Educacao` (`cd_instrucao`, `desc_instrucao`) VALUES (1, 'Analfabeto / Primário incompleto');
INSERT INTO `mvp_pesquisa`.`Educacao` (`cd_instrucao`, `desc_instrucao`) VALUES (2, 'Primário completo / Ginásio incompleto');
INSERT INTO `mvp_pesquisa`.`Educacao` (`cd_instrucao`, `desc_instrucao`) VALUES (3, 'Ginásio completo / Colégio incompleto');
INSERT INTO `mvp_pesquisa`.`Educacao` (`cd_instrucao`, `desc_instrucao`) VALUES (4, 'Colégio completo / Superior incompleto');
INSERT INTO `mvp_pesquisa`.`Educacao` (`cd_instrucao`, `desc_instrucao`) VALUES (5, 'Superio Completo');

COMMIT;


-- -----------------------------------------------------
-- Data for table `mvp_pesquisa`.`Posicao_Trabalho`
-- -----------------------------------------------------
START TRANSACTION;
USE `mvp_pesquisa`;
INSERT INTO `mvp_pesquisa`.`Posicao_Trabalho` (`cd_posicao_trabalho`, `desc_posicao_trabalho`) VALUES (1, 'Patrão');
INSERT INTO `mvp_pesquisa`.`Posicao_Trabalho` (`cd_posicao_trabalho`, `desc_posicao_trabalho`) VALUES (2, 'Diretor / Chefia');
INSERT INTO `mvp_pesquisa`.`Posicao_Trabalho` (`cd_posicao_trabalho`, `desc_posicao_trabalho`) VALUES (3, 'Diretor');
INSERT INTO `mvp_pesquisa`.`Posicao_Trabalho` (`cd_posicao_trabalho`, `desc_posicao_trabalho`) VALUES (4, 'Gerente com chefia de Funcionarios');
INSERT INTO `mvp_pesquisa`.`Posicao_Trabalho` (`cd_posicao_trabalho`, `desc_posicao_trabalho`) VALUES (5, 'Gerente');
INSERT INTO `mvp_pesquisa`.`Posicao_Trabalho` (`cd_posicao_trabalho`, `desc_posicao_trabalho`) VALUES (6, 'Quadro Médio');
INSERT INTO `mvp_pesquisa`.`Posicao_Trabalho` (`cd_posicao_trabalho`, `desc_posicao_trabalho`) VALUES (7, 'Funcionário Administrativo');

COMMIT;


-- -----------------------------------------------------
-- Data for table `mvp_pesquisa`.`Profissao`
-- -----------------------------------------------------
START TRANSACTION;
USE `mvp_pesquisa`;
INSERT INTO `mvp_pesquisa`.`Profissao` (`cd_profissao`, `desc_profissao`) VALUES (1, 'Diretor / Gerente');
INSERT INTO `mvp_pesquisa`.`Profissao` (`cd_profissao`, `desc_profissao`) VALUES (2, 'Profissionais cientistas / Intelectuais');
INSERT INTO `mvp_pesquisa`.`Profissao` (`cd_profissao`, `desc_profissao`) VALUES (3, 'Tecnicos / Profissionais Nível Médio');
INSERT INTO `mvp_pesquisa`.`Profissao` (`cd_profissao`, `desc_profissao`) VALUES (4, 'Trabalhadores de Apoio / Administrativo');
INSERT INTO `mvp_pesquisa`.`Profissao` (`cd_profissao`, `desc_profissao`) VALUES (5, 'Trabalhadores de Serviços / Vendedores Comerciais / Mercados');
INSERT INTO `mvp_pesquisa`.`Profissao` (`cd_profissao`, `desc_profissao`) VALUES (6, 'Trabalhadores Qualificados Agropecuária Floresta e Caça');
INSERT INTO `mvp_pesquisa`.`Profissao` (`cd_profissao`, `desc_profissao`) VALUES (7, 'Trabalhadores Qualificados Artesão ');
INSERT INTO `mvp_pesquisa`.`Profissao` (`cd_profissao`, `desc_profissao`) VALUES (8, 'Operadores de Instalação / Maquinas / Montagem');
INSERT INTO `mvp_pesquisa`.`Profissao` (`cd_profissao`, `desc_profissao`) VALUES (9, 'Ocupações Elementares');
INSERT INTO `mvp_pesquisa`.`Profissao` (`cd_profissao`, `desc_profissao`) VALUES (10, 'Menbros das Forças Armadas / Policia / Bombeiro');

COMMIT;


-- -----------------------------------------------------
-- Data for table `mvp_pesquisa`.`Respondente`
-- -----------------------------------------------------
START TRANSACTION;
USE `mvp_pesquisa`;
INSERT INTO `mvp_pesquisa`.`Respondente` (`cd_numero_registro`, `cd_individuo`, `cd_fk_tab_fonte`, `cd_cpf`, `nome`, `email`, `telefone_fixo`, `telefone_cel`, `cep`, `cd_fk_tab_estado`, `cd_fk_tab_cidade`, `cd_fk_tab_municipio`, `sexo`, `data_nascimento`, `cd_fk_tab_faixa_etaria`, `cd_fk_tab_estado_civil`, `classe_social`, `cd_fk_tab_educacao`, `cd_fk_tab_renda`, `cd_fk_tab_profissao`, `cd_fk_posicao_trabalho`, `moradia`, `moradia_lazer`, `auxiliar_do_lar`, `possui_carro`, `raca`) VALUES (1, 2, 1, '120120120-33', 'Fulano 1', 'fulano@fulano.com', '85.1234.1233', '85.99876.5432', '1234567-098', 1, 2, 2, 1, '2000-03-12', 1, 1, 'C', 3, 3, 4, 2, 2, 1, 1, 1, 2);
INSERT INTO `mvp_pesquisa`.`Respondente` (`cd_numero_registro`, `cd_individuo`, `cd_fk_tab_fonte`, `cd_cpf`, `nome`, `email`, `telefone_fixo`, `telefone_cel`, `cep`, `cd_fk_tab_estado`, `cd_fk_tab_cidade`, `cd_fk_tab_municipio`, `sexo`, `data_nascimento`, `cd_fk_tab_faixa_etaria`, `cd_fk_tab_estado_civil`, `classe_social`, `cd_fk_tab_educacao`, `cd_fk_tab_renda`, `cd_fk_tab_profissao`, `cd_fk_posicao_trabalho`, `moradia`, `moradia_lazer`, `auxiliar_do_lar`, `possui_carro`, `raca`) VALUES (2, 1, 2, '000111222-34', 'Fulano 2', 'fulano1f@email.com', '71.3456.7865', '71.98988.9999', '123456-098', 3, 4, 1, 2, '1967-04-12', 2, 2, 'B', 2, 2, 2, 3, 1, 1, 1, 1, 2);
INSERT INTO `mvp_pesquisa`.`Respondente` (`cd_numero_registro`, `cd_individuo`, `cd_fk_tab_fonte`, `cd_cpf`, `nome`, `email`, `telefone_fixo`, `telefone_cel`, `cep`, `cd_fk_tab_estado`, `cd_fk_tab_cidade`, `cd_fk_tab_municipio`, `sexo`, `data_nascimento`, `cd_fk_tab_faixa_etaria`, `cd_fk_tab_estado_civil`, `classe_social`, `cd_fk_tab_educacao`, `cd_fk_tab_renda`, `cd_fk_tab_profissao`, `cd_fk_posicao_trabalho`, `moradia`, `moradia_lazer`, `auxiliar_do_lar`, `possui_carro`, `raca`) VALUES (3, 3, 4, '45453788-62', 'Fulano 3', 'fufu@email.com', '51.2345.5432', '34.98977.0000', '456867-098', 4, 2, 3, 3, '2014-03-18', 3, 3, 'A', 1, 1, 1, 1, 3, 2, 1, 1, 1);

COMMIT;


-- -----------------------------------------------------
-- Data for table `mvp_pesquisa`.`Usuario_Admin`
-- -----------------------------------------------------
START TRANSACTION;
USE `mvp_pesquisa`;
INSERT INTO `mvp_pesquisa`.`Usuario_Admin` (`id_user_sistema`, `nome_user`, `config_user`, `senha_user`) VALUES (1, 'user', 'USER', '$2a$04$1.YhMIgNX/8TkCKGFUONWO1waedKhQ5KrnB30fl0Q01QKqmzLf.Zi');
INSERT INTO `mvp_pesquisa`.`Usuario_Admin` (`id_user_sistema`, `nome_user`, `config_user`, `senha_user`) VALUES (2, 'admin', 'ADMIN', '$2a$04$KNLUwOWHVQZVpXyMBNc7JOzbLiBjb9Tk9bP7KNcPI12ICuvzXQQKG');

COMMIT;

