-- MySQL Script generated by MySQL Workbench
-- Sun Dec  2 11:45:51 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

-- SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
-- SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
-- SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mvp_pesquisa
-- -----------------------------------------------------
-- Banco de Estudo da Cadeira de BD 1
-- DROP SCHEMA IF EXISTS mvp_pesquisa ;

-- -----------------------------------------------------
-- Schema mvp_pesquisa
--
-- Banco de Estudo da Cadeira de BD 1
-- -----------------------------------------------------
-- CREATE SCHEMA IF NOT EXISTS mvp_pesquisa DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ;
-- USE mvp_pesquisa ;

-- -----------------------------------------------------
-- Table mvp_pesquisa.Fonte
-- -----------------------------------------------------
-- DROP TABLE IF EXISTS Fonte ;

CREATE TABLE Fonte (
  cd_fonte INT NOT NULL AUTO_INCREMENT,
  nm_descricao VARCHAR(100) NOT NULL,
  PRIMARY KEY (cd_fonte));


-- -----------------------------------------------------
-- Table mvp_pesquisa.UF
-- -----------------------------------------------------
-- DROP TABLE IF EXISTS mvp_pesquisa.UF ;

CREATE TABLE UF (
  cd_uf INT NOT NULL AUTO_INCREMENT,
  sigla_uf CHAR(2) NOT NULL,
  nome VARCHAR(100) NOT NULL,
  PRIMARY KEY (cd_uf));


-- -----------------------------------------------------
-- Table mvp_pesquisa.Cidade
-- -----------------------------------------------------
-- DROP TABLE IF EXISTS mvp_pesquisa.Cidade ;

CREATE TABLE Cidade (
  cd_cidade INT NOT NULL AUTO_INCREMENT,
  nome_cidade VARCHAR(50) NULL,
  PRIMARY KEY (cd_cidade));


-- -----------------------------------------------------
-- Table mvp_pesquisa.Municipio
-- -----------------------------------------------------
-- DROP TABLE IF EXISTS mvp_pesquisa.Municipio ;

CREATE TABLE Municipio (
  cd_municipio INT NOT NULL AUTO_INCREMENT,
  nome_municipio VARCHAR(50) NOT NULL,
  PRIMARY KEY (cd_municipio));


-- -----------------------------------------------------
-- Table mvp_pesquisa.Faixa_Etaria
-- -----------------------------------------------------
-- DROP TABLE IF EXISTS mvp_pesquisa.Faixa_Etaria ;

CREATE TABLE Faixa_Etaria (
  cd_faixa_etaria INT NOT NULL AUTO_INCREMENT,
  desc_idade VARCHAR(20) NOT NULL COMMENT 'Multivalorado com as seguintes opções:\n1. menos de 20 anos\n2. 21 a 30 anos\n3. 31 a 40 anos\n4. 41 a 50 anos\n5. 51 a 60 anos\n6. 61 a 70 anos\n7. mais de 70 anos',
  PRIMARY KEY (cd_faixa_etaria));


-- -----------------------------------------------------
-- Table mvp_pesquisa.Estado_Civil
-- -----------------------------------------------------
-- DROP TABLE IF EXISTS mvp_pesquisa.Estado_Civil ;

CREATE TABLE Estado_Civil (
  cd_estado_civil INT NOT NULL AUTO_INCREMENT,
  desc_estado_civil VARCHAR(20) NULL COMMENT 'A descrição e multivalorada \n1. solteiro \n2. casado\n3. separado\n4. divorciado/desquitado\n5. viúvo ',
  PRIMARY KEY (cd_estado_civil));


-- -----------------------------------------------------
-- Table mvp_pesquisa.Renda
-- -----------------------------------------------------
-- DROP TABLE IF EXISTS mvp_pesquisa.Renda ;

CREATE TABLE Renda (
  cd_renda INT NOT NULL AUTO_INCREMENT,
  desc_renda VARCHAR(100) NULL COMMENT 'Descrição da renda:\n1. de 700 a 1024\n2. de 1025 a 1704\n3. de 1705 a 2832\n4. de 2833 a 5346\n5 . mais de 5347',
  PRIMARY KEY (cd_renda));


-- -----------------------------------------------------
-- Table mvp_pesquisa.Educacao
-- -----------------------------------------------------
-- DROP TABLE IF EXISTS mvp_pesquisa.Educacao ;

CREATE TABLE Educacao (
  cd_instrucao INT NOT NULL AUTO_INCREMENT,
  desc_instrucao VARCHAR(200) NOT NULL COMMENT 'Tipo:\n\n1 -> Analfabeto / primeiro incompleto\n2 -> Primário Completo / Ginásio Incompleto\n3 -> Ginásio Completo / Colégial Incompleto\n4 -> Colégio Completo / Superior Incompleto\n5 -> Superior Completo',
  PRIMARY KEY (cd_instrucao));


-- -----------------------------------------------------
-- Table mvp_pesquisa.Profissao
-- -----------------------------------------------------
-- DROP TABLE IF EXISTS mvp_pesquisa.Profissao ;

CREATE TABLE Profissao (
  cd_profissao INT UNSIGNED NOT NULL AUTO_INCREMENT,
  desc_profissao VARCHAR(255) NOT NULL COMMENT 'Descrição da Profissão (Alfanumérico, Tamanho: 40). Valores possíveis: \n1. diretor e gerente\n2. profissionais cientistas e intelectuais\n3. tecnicos e profissões nível médio\n4. trabalhadores de apoio administrativo\n5. trabalhadores de serviços, vendedores comerciais e mercado\n6. trababalhores qualificados agropecuária floresta e caça\n7. trabalhadores qualificados artesãos\n8. operadores de instalações, maquinas e montagens\n9. ocupações elementares\n0. membros das FAs policia bombeiros',
  PRIMARY KEY (cd_profissao));


-- -----------------------------------------------------
-- Table mvp_pesquisa.Posicao_Trabalho
-- -----------------------------------------------------
-- DROP TABLE IF EXISTS mvp_pesquisa.Posicao_Trabalho ;

CREATE TABLE Posicao_Trabalho (
  cd_posicao_trabalho INT NOT NULL AUTO_INCREMENT,
  desc_posicao_trabalho VARCHAR(255) NOT NULL COMMENT 'Descrição da da Posição Trabalho (Alfanumérico, Tamanho: 20). Valores possíveis:  \n\n1. patrão\n2. diretor com chefia de funcionários\n3. diretor\n4. gerente com chefia de funcionários\n5. gerente\n6. quadro médio \n7. funcionário administrativo',
  PRIMARY KEY (cd_posicao_trabalho));


-- -----------------------------------------------------
-- Table mvp_pesquisa.Respondente
-- -----------------------------------------------------
-- DROP TABLE IF EXISTS mvp_pesquisa.Respondente ;

CREATE TABLE Respondente (
  cd_numero_registro INT NOT NULL AUTO_INCREMENT,
  cd_individuo INT NOT NULL,
  cd_fk_tab_fonte INT NOT NULL,
  cd_cpf VARCHAR(12) NOT NULL,
  nome VARCHAR(100) NOT NULL,
  email VARCHAR(40) NOT NULL,
  telefone_fixo VARCHAR(50) NOT NULL,
  telefone_cel VARCHAR(50) NOT NULL,
  cep VARCHAR(20) NOT NULL,
  cd_fk_tab_estado INT NOT NULL,
  cd_fk_tab_cidade INT NOT NULL,
  cd_fk_tab_municipio INT NOT NULL,
  sexo INT NOT NULL COMMENT 'Sexo Tipo Alpha Numerico \n1 -> Masculino\n2 -> Feminio\n3-> Indefinido',
  data_nascimento VARCHAR(255) NOT NULL COMMENT '\n',
  cd_fk_tab_faixa_etaria INT NOT NULL,
  cd_fk_tab_estado_civil INT NOT NULL,
  classe_social CHAR(1) NOT NULL COMMENT 'Tipos:\n1 -> A;\n2 -> B;\n3 -> C;\n4 -> D;\n5 -> E;',
  cd_fk_tab_educacao INT NOT NULL,
  cd_fk_tab_renda INT NOT NULL,
  cd_fk_tab_profissao INT NOT NULL,
  cd_fk_posicao_trabalho INT NOT NULL,
  moradia INT NOT NULL COMMENT 'Tipo:\n1 -> Casa Própria;\n2 -> Apartamemto Próprio\n3 -> Casa Alugada\n4 -> Apartemento Alugado',
  moradia_lazer INT NOT NULL COMMENT 'Tipo:\n\n1 -> Casa própria na praia;\n2 -> Casa própria no campo;',
  auxiliar_do_lar INT NOT NULL COMMENT 'Tipo:\n\n1 -> Empregada permanente;\n2 -> Diarista;',
  possui_carro TINYINT NOT NULL,
  raca INT NOT NULL COMMENT 'Tipo\n\n1 -> Branca\n2 -> Preta\n3 -> Amarela\n4 -> Parda\n5 -> Indígena\n\n',
  PRIMARY KEY (cd_numero_registro));


-- -----------------------------------------------------
-- Table mvp_pesquisa.Telefones
-- -----------------------------------------------------
-- DROP TABLE IF EXISTS mvp_pesquisa.Telefones ;

CREATE TABLE Telefones (
  id INT NOT NULL,
  Telefone_Fixo VARCHAR(100) NULL,
  Telefone_Cel VARCHAR(100) NULL,
  PRIMARY KEY (id));


-- -----------------------------------------------------
-- Table mvp_pesquisa.Usuario_Admin
-- -----------------------------------------------------
-- DROP TABLE Usuario_Admin ;

CREATE TABLE Useradmin (
  id INT NOT NULL AUTO_INCREMENT,
  username VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL,
  role VARCHAR(255) NOT NULL,
  PRIMARY KEY (id));

CREATE TABLE AccountCredentials (
  id int not null auto_increment,
  username varchar(255) not null ,
  password varchar(255) not null,
  primary key (id)
);

-- -- -- SET SQL_MODE=@OLD_SQL_MODE;
-- -- SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
-- SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;



-- -----------------------------------------------------
-- Data for table UF
-- -----------------------------------------------------

Insert Into uf (sigla_uf, nome)
Values ('AC', 'Acre');
Insert Into uf (sigla_uf, nome)
Values ('AL', 'Alagoas');
Insert Into uf (sigla_uf, nome)
Values ('AM', 'Amazonas');
Insert Into uf (sigla_uf, nome)
Values ('AP', 'Amapá');
Insert Into uf (sigla_uf, nome)
Values ('BA', 'Bahia');
Insert Into uf (sigla_uf, nome)
Values ('CE', 'Ceará');
Insert Into uf (sigla_uf, nome)
Values ('DF', 'Distrito Federal');
Insert Into uf (sigla_uf, nome)
Values ('ES', 'Espírito Santo');
Insert Into uf (sigla_uf, nome)
Values ('GO', 'Goiás');
Insert Into uf (sigla_uf, nome)
Values ('MA', 'Maranhão');
Insert Into uf (sigla_uf, nome)
Values ('MG', 'Minas Gerais');
Insert Into uf (sigla_uf, nome)
Values ('MS', 'Mato Grosso do Sul');
Insert Into uf (sigla_uf, nome)
Values ('MT', 'Mato Grosso');
Insert Into uf (sigla_uf, nome)
Values ('PA', 'Pará');
Insert Into uf (sigla_uf, nome)
Values ('PB', 'Paraíba');
Insert Into uf (sigla_uf, nome)
Values ('PE', 'Pernambuco');
Insert Into uf (sigla_uf, nome)
Values ('PI', 'Piauí');
Insert Into uf (sigla_uf, nome)
Values ('PR', 'Paraná');
Insert Into uf (sigla_uf, nome)
Values ('RJ', 'Rio de Janeiro');
Insert Into uf (sigla_uf, nome)
Values ('RN', 'Rio Grande do Norte');
Insert Into uf (sigla_uf, nome)
Values ('RO', 'Rondônia');
Insert Into uf (sigla_uf, nome)
Values ('RR', 'Roraima');
Insert Into uf (sigla_uf, nome)
Values ('RS', 'Rio Grande do Sul');
Insert Into uf (sigla_uf, nome)
Values ('SC', 'Santa Catarina');
Insert Into uf (sigla_uf, nome)
Values ('SE', 'Sergipe');
Insert Into uf (sigla_uf, nome)
Values ('SP', 'São Paulo');
Insert Into uf (sigla_uf, nome)
Values ('TO', 'Tocantins');





-- -----------------------------------------------------
-- Data for table mvp_pesquisa.Fonte
-- -----------------------------------------------------
-- START TRANSACTION;
-- USE mvp_pesquisa;
INSERT INTO Fonte (cd_fonte, nm_descricao) VALUES (1, 'Casa Bahia');
INSERT INTO Fonte (cd_fonte, nm_descricao) VALUES (2, 'Diario do Nordeste');
INSERT INTO Fonte (cd_fonte, nm_descricao) VALUES (3 , 'Data Folha');
INSERT INTO Fonte (cd_fonte, nm_descricao) VALUES (4, 'Ibope');

-- COMMIT;


-- -----------------------------------------------------
-- Data for table mvp_pesquisa.Faixa_Etaria
-- -----------------------------------------------------
-- START TRANSACTION;
-- USE mvp_pesquisa;
INSERT INTO Faixa_Etaria (cd_faixa_etaria, desc_idade) VALUES (1, 'menos de 20 anos');
INSERT INTO Faixa_Etaria (cd_faixa_etaria, desc_idade) VALUES (2, '21 a 30 anos');
INSERT INTO Faixa_Etaria (cd_faixa_etaria, desc_idade) VALUES (3, '31 a 40 anos');
INSERT INTO Faixa_Etaria (cd_faixa_etaria, desc_idade) VALUES (4, '41 a 50 anos');
INSERT INTO Faixa_Etaria (cd_faixa_etaria, desc_idade) VALUES (5, '51 a 60 anos');
INSERT INTO Faixa_Etaria (cd_faixa_etaria, desc_idade) VALUES (6, '61 a 70 anos ');
INSERT INTO Faixa_Etaria (cd_faixa_etaria, desc_idade) VALUES (7, 'mais de 70 anos');

-- COMMIT;


-- -----------------------------------------------------
-- Data for table mvp_pesquisa.Estado_Civil
-- -----------------------------------------------------
-- START TRANSACTION;
-- USE mvp_pesquisa;
INSERT INTO Estado_Civil (cd_estado_civil, desc_estado_civil) VALUES (1, 'solteiro');
INSERT INTO Estado_Civil (cd_estado_civil, desc_estado_civil) VALUES (2, 'separado');
INSERT INTO Estado_Civil (cd_estado_civil, desc_estado_civil) VALUES (3, 'divorciado');
INSERT INTO Estado_Civil (cd_estado_civil, desc_estado_civil) VALUES (4, 'viuvo');

-- COMMIT;


-- -----------------------------------------------------
-- Data for table Renda
-- -----------------------------------------------------
-- START TRANSACTION;
-- USE mvp_pesquisa;
INSERT INTO Renda (cd_renda, desc_renda) VALUES (1, 'R$ 700,00 a R$ 1.024,00');
INSERT INTO Renda (cd_renda, desc_renda) VALUES (2, 'R$ 1.025,00 a R$ 1.704,00');
INSERT INTO Renda (cd_renda, desc_renda) VALUES (3, 'R$ 1.705,00 a R$ 2.832,00');
INSERT INTO Renda (cd_renda, desc_renda) VALUES (4, 'R$ 2.833,00 a R$ 5.346,00');
INSERT INTO Renda (cd_renda, desc_renda) VALUES (5, 'acima de R$ 5.347,00');

-- COMMIT;


-- -----------------------------------------------------
-- Data for table Educacao
-- -----------------------------------------------------
-- START TRANSACTION;
-- USE mvp_pesquisa;
INSERT INTO Educacao (cd_instrucao, desc_instrucao) VALUES (1, 'Analfabeto / Primário incompleto');
INSERT INTO Educacao (cd_instrucao, desc_instrucao) VALUES (2, 'Primário completo / Ginásio incompleto');
INSERT INTO Educacao (cd_instrucao, desc_instrucao) VALUES (3, 'Ginásio completo / Colégio incompleto');
INSERT INTO Educacao (cd_instrucao, desc_instrucao) VALUES (4, 'Colégio completo / Superior incompleto');
INSERT INTO Educacao (cd_instrucao, desc_instrucao) VALUES (5, 'Superio Completo');

-- COMMIT;


-- -----------------------------------------------------
-- Data for table Profissao
-- -----------------------------------------------------
-- START TRANSACTION;
-- USE mvp_pesquisa;
INSERT INTO Profissao (cd_profissao, desc_profissao) VALUES (1, 'Diretor / Gerente');
INSERT INTO Profissao (cd_profissao, desc_profissao) VALUES (2, 'Profissionais cientistas / Intelectuais');
INSERT INTO Profissao (cd_profissao, desc_profissao) VALUES (3, 'Tecnicos / Profissionais Nível Médio');
INSERT INTO Profissao (cd_profissao, desc_profissao) VALUES (4, 'Trabalhadores de Apoio / Administrativo');
INSERT INTO Profissao (cd_profissao, desc_profissao) VALUES (5, 'Trabalhadores de Serviços / Vendedores Comerciais / Mercados');
INSERT INTO Profissao (cd_profissao, desc_profissao) VALUES (6, 'Trabalhadores Qualificados Agropecuária Floresta e Caça');
INSERT INTO Profissao (cd_profissao, desc_profissao) VALUES (7, 'Trabalhadores Qualificados Artesão ');
INSERT INTO Profissao (cd_profissao, desc_profissao) VALUES (8, 'Operadores de Instalação / Maquinas / Montagem');
INSERT INTO Profissao (cd_profissao, desc_profissao) VALUES (9, 'Ocupações Elementares');
INSERT INTO Profissao (cd_profissao, desc_profissao) VALUES (10, 'Menbros das Forças Armadas / Policia / Bombeiro');

-- COMMIT;


-- -----------------------------------------------------
-- Data for table Posicao_Trabalho
-- -----------------------------------------------------
-- START TRANSACTION;
-- USE mvp_pesquisa;
INSERT INTO Posicao_Trabalho (cd_posicao_trabalho, desc_posicao_trabalho) VALUES (1, 'Patrão');
INSERT INTO Posicao_Trabalho (cd_posicao_trabalho, desc_posicao_trabalho) VALUES (2, 'Diretor / Chefia');
INSERT INTO Posicao_Trabalho (cd_posicao_trabalho, desc_posicao_trabalho) VALUES (3, 'Diretor');
INSERT INTO Posicao_Trabalho (cd_posicao_trabalho, desc_posicao_trabalho) VALUES (4, 'Gerente com chefia de Funcionarios');
INSERT INTO Posicao_Trabalho (cd_posicao_trabalho, desc_posicao_trabalho) VALUES (5, 'Gerente');
INSERT INTO Posicao_Trabalho (cd_posicao_trabalho, desc_posicao_trabalho) VALUES (6, 'Quadro Médio');
INSERT INTO Posicao_Trabalho (cd_posicao_trabalho, desc_posicao_trabalho) VALUES (7, 'Funcionário Administrativo');

-- COMMIT;

-- -----------------------------------------------------
-- Data for table Respondente
-- -----------------------------------------------------

INSERT INTO Respondente (`cd_numero_registro`, `cd_individuo`, `cd_fk_tab_fonte`, `cd_cpf`, `nome`, `email`, `telefone_fixo`, `telefone_cel`, `cep`, `cd_fk_tab_estado`, `cd_fk_tab_cidade`, `cd_fk_tab_municipio`, `sexo`, `data_nascimento`, `cd_fk_tab_faixa_etaria`, `cd_fk_tab_estado_civil`, `classe_social`, `cd_fk_tab_educacao`, `cd_fk_tab_renda`, `cd_fk_tab_profissao`, `cd_fk_posicao_trabalho`, `moradia`, `moradia_lazer`, `auxiliar_do_lar`, `possui_carro`, `raca`) VALUES (1, 2, 1, '120120120-33', 'Fulano 1', 'fulano@fulano.com', '85.1234.1233', '85.99876.5432', '1234567-098', 1, 2, 2, 1, '65522558', 1, 1, 'C', 3, 3, 4, 2, 2, 1, 1, 1, 2);
INSERT INTO Respondente (`cd_numero_registro`, `cd_individuo`, `cd_fk_tab_fonte`, `cd_cpf`, `nome`, `email`, `telefone_fixo`, `telefone_cel`, `cep`, `cd_fk_tab_estado`, `cd_fk_tab_cidade`, `cd_fk_tab_municipio`, `sexo`, `data_nascimento`, `cd_fk_tab_faixa_etaria`, `cd_fk_tab_estado_civil`, `classe_social`, `cd_fk_tab_educacao`, `cd_fk_tab_renda`, `cd_fk_tab_profissao`, `cd_fk_posicao_trabalho`, `moradia`, `moradia_lazer`, `auxiliar_do_lar`, `possui_carro`, `raca`) VALUES (2, 1, 2, '000111222-34', 'Fulano 2', 'fulano1f@email.com', '71.3456.7865', '71.98988.9999', '123456-098', 3, 4, 1, 2, '125445121', 2, 2, 'B', 2, 2, 2, 3, 1, 1, 1, 1, 2);
INSERT INTO Respondente (`cd_numero_registro`, `cd_individuo`, `cd_fk_tab_fonte`, `cd_cpf`, `nome`, `email`, `telefone_fixo`, `telefone_cel`, `cep`, `cd_fk_tab_estado`, `cd_fk_tab_cidade`, `cd_fk_tab_municipio`, `sexo`, `data_nascimento`, `cd_fk_tab_faixa_etaria`, `cd_fk_tab_estado_civil`, `classe_social`, `cd_fk_tab_educacao`, `cd_fk_tab_renda`, `cd_fk_tab_profissao`, `cd_fk_posicao_trabalho`, `moradia`, `moradia_lazer`, `auxiliar_do_lar`, `possui_carro`, `raca`) VALUES (3, 3, 4, '45453788-62', 'Fulano 3', 'fufu@email.com', '51.2345.5432', '34.98977.0000', '456867-098', 4, 2, 3, 3, '2245451', 3, 3, 'A', 1, 1, 1, 1, 3, 2, 1, 1, 1);



-- -----------------------------------------------------
-- Data for table Usuario_Admin
-- -----------------------------------------------------
START TRANSACTION;
USE mvp_pesquisa;
INSERT INTO Useradmin (id, username, password, role) VALUES (1, 'user', '$2a$04$1.YhMIgNX/8TkCKGFUONWO1waedKhQ5KrnB30fl0Q01QKqmzLf.Zi', 'USER');
INSERT INTO Useradmin (id, username, password, role) VALUES (2, 'admin', '$2a$04$KNLUwOWHVQZVpXyMBNc7JOzbLiBjb9Tk9bP7KNcPI12ICuvzXQQKG', 'ADMIN');

-- COMMIT;



